version: "3.7"
name: werp-echo-api
volumes:
  mysql_data:
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: .
    volumes:
      - .:/app
    command: air -c .air.toml
    depends_on:
      - db
    ports:
      - 3000:3000
