version: "3.7"
name: ebra
volumes:
  mysql_data:
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  app:
    build: .
    volumes:
      - .:/app
    command: air -c .air.toml
    depends_on:
      - db
    ports:
      - 3000:3000
