version: "3.7"
name: ebra
volumes:
  db_volume:
services:
  db:
    image: mysql:8.0
    volumes:
      - db_volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  app:
    depends_on:
      - db
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file: .env
    environment:
      APP_ENV: development
    command: air -c .air.toml
