package middlewares_test

import (
	"testing"

	"github.com/google/uuid"
	"github.com/reizt/ebra/middlewares"
	"github.com/stretchr/testify/assert"
)

// Ensure a token generated by `GenerateJwt` and one by `ValidateJwt` are the same.
func TestJwt(t *testing.T) {
	sessionId := uuid.New().String()
	tokenString, err := middlewares.GenerateJwt(sessionId)
	if err != nil {
		t.Fatalf("got error: %v", err)
	}
	claims, err := middlewares.ValidateJwt(tokenString)
	if err != nil {
		t.Fatalf("got error: %v", err)
	}
	assert.Equal(t, sessionId, claims["sessionId"])
}
